adding homework CSharpAdvanced
KrisAramis/Automation_using_.NET pull request #13
Opened 2023-07-18 22:52 UTC by KrisAramis

Added Homework for CSharpAdvanced

2023-07-19 11:06 UTC, dnnyhlwdplc requested changes

2023-07-19 11:06 UTC, dnnyhlwdplc commented on CSharpOOP2/Helper.cs
> +    public static void Refuel(Car car, double liters)
this :)

2023-07-19 11:06 UTC, dnnyhlwdplc commented on CSharpOOP2/Helper.cs
> +
Please review spacing :) 1 space between class members

2023-07-19 11:06 UTC, dnnyhlwdplc commented on Camomile.cs
> +public class Camomile:Flower
It is okay for this HW, but in future if you will see empty class it will mean that there is an issue with architecture :)

2023-07-19 11:06 UTC, dnnyhlwdplc commented on Flower.cs
> +        set => _color = value ?? throw new ArgumentNullException(nameof(value));
nice!

2023-07-19 11:06 UTC, dnnyhlwdplc commented on FlowerRepaint.cs
> +public class FlowerRepaint<T>
where <T> is used for this class?

2023-07-19 11:06 UTC, dnnyhlwdplc commented on FlowerRepaint.cs
> +    public static void RepaintFlower(Flower flower, string newcolor, double upsell = 0.15)
Flower -> T

2023-07-19 11:06 UTC, dnnyhlwdplc commented on Program.cs
> +        static T ReturnFirstElement<T>(List<T> elements)
method should not be placed in method

2023-07-19 11:06 UTC, dnnyhlwdplc commented on Program.cs
> +        bool success = int.TryParse(Console.ReadLine(), out rosesAmount);
it is great that you added safe parsing :)

2023-07-19 11:06 UTC, dnnyhlwdplc commented on Program.cs
> +        void PrintReceipt<T>(T flower, int amount) where T : Flower
same

2023-07-19 11:06 UTC, dnnyhlwdplc commented on FlowerRepaint.cs
> +    public static void RepaintFlower(Flower flower, string newcolor, double upsell = 0.15)
great that you made upsell as a param!

2023-07-19 11:06 UTC, dnnyhlwdplc commented on Program.cs
> +        static double ReturnPriceforBouquet<T>(T flower, int flowersAmount) where T : Flower
add this generic methods in separate class

2023-07-20 14:07 UTC, KrisAramis commented on Camomile.cs
> +public class Camomile:Flower
noted)

2023-07-24 09:58 UTC, dnnyhlwdplc approved these changes

2023-08-20 15:28 UTC, merged